### ISSUE TITLE
Not working plugin

### ISSUE THREAD

**Issue by AleksandrMikoshi** [mattermost/mattermost-plugin-calls#119] opened 2022-06-20 11:46 UTC
Hello.
We find the following problem:
The MatterMost website is accessible from the wild web, but calls are made only when the VPN is enabled (within the same network as the mattermost server).
All DNS records lead to an external MM address, an external google server is used as an ICE server.
If you turn off the VPN - there will be no sound.

Most likely the problem is in open / closed ports, could you tell me which port should be opened from the MM side for the calls plugin to work correctly?

**Comment by streamer45** [comment] 2022-06-20 13:47
@AleksandrMikoshi The port that needs to be open is what is configured as `RTC Server Port`. It defaults to `8443` but can be changed. This needs to be open as UDP incoming on the Mattermost instance hosting the plugin.

**Comment by masterkain** [comment] 2022-06-20 18:18
perhaps this fact that installing the plugin and crossing fingers isn't enough (like I believed at first) but can require additional networking configuration is something that can be highlighted in the readme; my solution for EKS is here https://github.com/mattermost/mattermost-plugin-calls/issues/101#issuecomment-1153010021 in case we want to write a section

**Comment by streamer45** [comment] 2022-06-20 18:26
Totally, that could be a pretty good contribution :)

**Comment by AleksandrMikoshi** [comment] 2022-06-29 06:28
I opened the port, but the problem persists.
with VPN the call works, without VPN (or when VPN is disabled) the call does not work.
Any other ideas?)
<img width="270" alt="Screenshot 2022-06-29 at 9 26 05 AM" src="https://user-images.githubusercontent.com/79300692/176366710-7ba6ee5f-e0e0-448d-81f3-1aac5f474c4d.png">
<img width="459" alt="Screenshot 2022-06-29 at 9 26 17 AM" src="https://user-images.githubusercontent.com/79300692/176366720-0918cd45-4b10-476a-bd13-8b7a8d51e833.png">

**Comment by streamer45** [comment] 2022-06-30 10:48
@AleksandrMikoshi It's likely you need to set the "ICE Host Override" config option to the client facing host/IP. That would usually be the public IP address that clients can use to reach the Mattermost instance on the configured port (8443). Of course depending on your deployment that could be a gateway or some other network component in between. I'd have to know more about your specific setup to help further.

**Comment by AleksandrMikoshi** [comment] 2022-06-30 20:32
We have one mattermost server, Starter. There are no additional gateways/components.
Internal (AD) and external (provider) DNS servers have one entry (external IP).
Port 8443 is allowed on all network equipment, allowed on the host itself.
We don't have our own ICE or STUN servers. As a STUN - stun:stun.l.google.com:19302
In the "ICE Host Override" section, I specified the external IP and server name, the problem persists:
- With VPN calls work properly
- If the VPN is turned off for one of the callers - there is no sound (in both directions)
- If the VPN is turned off for both - calls work every other time, you need to start a call and reconnect to it

If you are interested in any specific information, I am ready to provide

**Comment by streamer45** [comment] 2022-07-01 08:20
Yes, would be good to get some client logs (JS console) for these scenarios:

- Client with VPN on (calls are working)
- Client with VPN off (no sound)

**Comment by AleksandrMikoshi** [comment] 2022-07-01 08:54
The first three screenshots are with the VPN turned on
<img width="1272" alt="VPN_on_1" src="https://user-images.githubusercontent.com/79300692/176861207-18fa03ba-4d5b-47c9-bd92-18387fdb49ac.png">
<img width="1281" alt="VPN_on_2" src="https://user-images.githubusercontent.com/79300692/176861229-a2a74956-ebc7-4eeb-a2f4-7287ebda4a47.png">
<img width="1283" alt="VPN_on_3" src="https://user-images.githubusercontent.com/79300692/176861237-d9b1acdb-5cd2-48d4-a8d9-942b97a33660.png">

the other two are with the VPN turned off
<img width="1289" alt="VPN_off_1" src="https://user-images.githubusercontent.com/79300692/176861263-074cf451-0b7a-487d-875a-c51a2daed7ca.png">
<img width="1277" alt="VPN_off_2" src="https://user-images.githubusercontent.com/79300692/176861272-8a0c7b7f-6f55-47c0-bfe4-3c7ce86c9828.png">

**Comment by streamer45** [comment] 2022-07-01 09:24
Thanks, looking at those I assume this is the host running Mattermost:

![image](https://user-images.githubusercontent.com/1832946/176864083-5e147eb2-6992-42fa-a994-9bcf48c1ebf3.png)

The connection in your second case is clearly failing which would suggests that the host/port is not directly reachable from the client. Using the VPN may affect that.

At this point I'd probably verify UDP packets can be sent by the client and received on the server using some tool like netcat (something like https://www.ibm.com/support/pages/udp-connectivity-testing for example).

**Comment by AleksandrMikoshi** [comment] 2022-07-01 11:29
netcat check:
- without VPN
<img width="448" alt="Screenshot 2022-07-01 at 2 05 40 PM" src="https://user-images.githubusercontent.com/79300692/176883240-b2ce750f-f357-4eb0-ba80-897d63cb3715.png">

- with VPN
<img width="442" alt="Screenshot 2022-07-01 at 2 06 19 PM" src="https://user-images.githubusercontent.com/79300692/176883262-08cc53b2-e6b2-4e68-abeb-2a35ea922022.png">

what kind of IP "84.201.183.9" I have no idea

**Comment by streamer45** [comment] 2022-07-01 11:36
> what kind of IP "84.201.183.9" I have no idea

Okay, then what do you have configured as "ICE Host Override"? I'd expect that to be set to the 51.250.xxx host you used there to check. Bear in mind you will have to restart the plugin to have that option take effect.

**Comment by AleksandrMikoshi** [comment] 2022-07-01 12:26
21.250.xxx this is the host directly to MatterMost. He is listed in the ICE Host Override

**Comment by streamer45** [comment] 2022-07-04 14:11
@AleksandrMikoshi To confirm, could you share the content of `PluginSettings.Plugins.com.mattermost.calls` from `config.json`? It looks like the wrong host is returned to clients which is clearly causing some issues.

Also, please feel free to reach out internally on our [community server](https://community.mattermost.com/) if you prefer to share privately. You can find me as `@claudio.costa`.

**Comment by niksprv** [comment] 2022-07-08 17:28
Hello @AleksandrMikoshi. I have exactly the same problem. Did you find the solution?

**Comment by AleksandrMikoshi** [comment] 2022-07-08 20:01
Hello.
Didn't solve the problem, went on vacation :)
The problem persists, I attach the plugin config in the file config.json

```
"com.mattermost.calls": {
                "allowenablecalls": true,
                "defaultenabled": true,
                "icehostoverride": "51.250.83.205",
                "iceservers": "stun:stun.l.google.com:19302",
                "maxcallparticipants": 0,
                "rtcdserviceurl": "",
                "udpserverport": 8443
            },
```

**Comment by streamer45** [comment] 2022-07-09 13:51
@AleksandrMikoshi Okay, if the override is set to that IP then that's the host that should be sent to the clients, not some other IP. I'd expect to see a host candidate such as `51.250.83.205  8443 typ host` in client logs. At this point it may be useful to see some server logs as well, especially after restarting (disabling and enabling) the plugin.

@niksprv It may seem a similar issue in terms of results (not being able to connect off the VPN) but without some logs it's impossible to say as it could easily be due to a completely different reason.

**Comment by AleksandrMikoshi** [comment] 2022-07-18 06:49
Hi
Updated the plugin to version 0.7.0 the problem remains.
In the logs regarding the plugin, there is only a similar error
{"timestamp":"2022-07-18 09:22:12.468 +03:00","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/ web_conn.go:834","user_id":"uip8pp68pffx8gg6sbs8gw1sar","error":"read tcp xxx.xxx.xxx.131:443->xxx.xxx.xxx.96:35354: i/o timeout"}

Added a proxy server for mattermost, port 8443 open

xxx.xxx.xxx.131 - internal IP address of mattermost
xxx.xxx.xxx.96 - proxy internal IP address

The external address of mattermost remains the same (it is also specified in the plugin settings in "ICE Host Override" - 51.250.xxx.xxx

In the browser console the following
<img width="1289" alt="Screenshot 2022-07-18 at 9 25 26 AM" src="https://user-images.githubusercontent.com/79300692/179457993-a1471a4b-a7aa-43a2-aac7-bd7e8038ed7e.png">
<img width="1289" alt="Screenshot 2022-07-18 at 9 25 44 AM" src="https://user-images.githubusercontent.com/79300692/179458005-2212abf2-13f1-47e9-beb5-e737ef4334fc.png">

**Comment by streamer45** [comment] 2022-07-18 16:42
That actually looks better as the right host (`51.250.xxx.xxx`) is now correctly advertised and client is even receiving media tracks meaning it's likely connecting at least briefly. One thing to try would be to remove any STUN server from config which may be causing some issues.

**Comment by AleksandrMikoshi** [comment] 2022-07-19 15:28
I removed all STUN servers, same result

"com.mattermost.calls": {
                "allowenablecalls": false,
                "defaultenabled": false,
                "icehostoverride": "51.250.xxx.xxx",
                "iceservers": "",
                "iceserversconfigs": "",
                "maxcallparticipants": 0,
                "rtcdserviceurl": "",
                "serversideturn": false,
                "turncredentialsexpirationminutes": 1440,
                "turnstaticauthsecret": "",
                "udpserverport": 8443
            },

<img width="1289" alt="Screenshot 2022-07-18 at 9 25 26 AM" src="https://user-images.githubusercontent.com/79300692/179788979-f860dca0-eec4-48b2-8970-5085ebc11fbe.png">
<img width="1289" alt="Screenshot 2022-07-18 at 9 25 44 AM" src="https://user-images.githubusercontent.com/79300692/179789002-5e99afe0-847e-4bfc-b790-6947f73a6459.png">

**Comment by AleksandrMikoshi** [comment] 2022-07-20 06:29
@streamer45 Hello.
Yes, I restarted the plugin, reloaded the config
<img width="1256" alt="20 07_1" src="https://user-images.githubusercontent.com/79300692/179912248-2a14c932-de91-49bd-89a1-6c6a36884735.png">
<img width="1289" alt="20 07_2" src="https://user-images.githubusercontent.com/79300692/179912258-6213910f-ffdb-44af-86a5-b2a4a78cfae3.png">
.

**Comment by streamer45** [comment] 2022-07-20 08:49
Thanks, so we can likely assume data is going through the right host/port but somehow disconnecting after a few seconds. To help further I'd need to understand a bit more about your infrastructure. Do you have a diagram/info you can share?

At this point, it would be helpful to temporarily run Mattermost with the `PION_LOG_TRACE=all` environment flag set and reproduce again to generate some debug logs. Since this is getting a bit more involved I'd encourage you to join our community server (https://community.mattermost.com/) so we can work together a bit more efficiently.

**Comment by zen-jedi** [comment] 2022-07-28 05:02
> I removed all STUN servers, same result
> 
> "com.mattermost.calls": { "allowenablecalls": false, "defaultenabled": false, "icehostoverride": "51.250.xxx.xxx", "iceservers": "", "iceserversconfigs": "", "maxcallparticipants": 0, "rtcdserviceurl": "", "serversideturn": false, "turncredentialsexpirationminutes": 1440, "turnstaticauthsecret": "", "udpserverport": 8443 },
> 
> <img alt="Screenshot 2022-07-18 at 9 25 26 AM" width="1289" src="https://user-images.githubusercontent.com/79300692/179788979-f860dca0-eec4-48b2-8970-5085ebc11fbe.png">
> 
> <img alt="Screenshot 2022-07-18 at 9 25 44 AM" width="1289" src="https://user-images.githubusercontent.com/79300692/179789002-5e99afe0-847e-4bfc-b790-6947f73a6459.png">

Hi, same issue, installed call plugin 0.7.0 in gitlab omnibus mattemost 7.0, where rtcd not started on port 8443 inside container.

**Comment by streamer45** [comment] 2022-07-28 07:28
> Hi, same issue, installed call plugin 0.7.0 in gitlab omnibus mattemost 7.0, where rtcd not started on port 8443 inside container.

@zen-jedi I'd likely need to see some logs (both client and server) in order to help. Please feel free to reach out internally on our [community server](https://community.mattermost.com/) if you prefer to share privately. You can find me as `@claudio.costa`.

**Comment by streamer45** [comment] 2022-08-04 07:43
Closing this for now as the reported issues have been resolved.

**Closed by streamer45** 2022-08-04 07:43 UTC

**Comment by it-smsnv** [comment] 2023-11-07 12:08
How did you solve the problem in the end?

**Comment by MrakoMaks** [comment] 2023-12-10 11:20
> Closing this for now as the reported issues have been resolved.

How did you solve the problem in the end?

**Comment by zen-jedi** [comment] 2023-12-10 13:54
> How did you solve the problem in the end?

for me helped set same ip my mm server to ICE Host Override and set blank config in ICE Servers Configuration, also set false flag in Server Side TURN
