### ISSUE TITLE
TypeError: i is not iterable

### ISSUE THREAD

**Issue by gohrner** [mattermost/mattermost-plugin-calls#643] opened 2024-02-22 14:22 UTC
Sometimes, but not very often (but also more than once), following happens / happened - I think it's related to Calls, as I've never seen it before:

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/26199042/62b68b78-a3a3-46ac-982f-72549d113c98)

```plain
TypeError: i is not iterable
    at /static/1927.3c9b4bd5c860163d5e9b.js:1:2303272
    at Array.forEach (<anonymous>)
    at Re (/static/1927.3c9b4bd5c860163d5e9b.js:1:2303227)
    at Function.mapToProps (/static/1927.3c9b4bd5c860163d5e9b.js:1:2304226)
    at n (/static/4617.edf7898712324c636e94.js:2:9042)
    at /static/4617.edf7898712324c636e94.js:2:10469
    at /static/4617.edf7898712324c636e94.js:2:10511
    at e.l (/static/4617.edf7898712324c636e94.js:2:5800)
    at r.handleChangeWrapper (/static/4617.edf7898712324c636e94.js:2:4017)
    at /static/4617.edf7898712324c636e94.js:2:4410
iu @ /static/1542.c90979d….js:2
```

Mattermost Team Edition
Mattermost Version: 8.1.10
Database Schema Version: 113
Build Number: 7877636995
Database: postgres

Calls (com.mattermost.calls - 0.23.1)

Host OS: Debian GNU/Linux 12.5 "Bookworm", x64
Browser: Chromium 121.0.6167.160 (Offizieller Build) snap (64-Bit) (on Ubuntu 22.04)

Besides that occasional error, Calls works quite well.

**Comment by streamer45** [comment] 2024-02-23 00:32
@gohrner Sounds like a duplicate of https://github.com/mattermost/mattermost-plugin-calls/issues/630

The quickest solution is to upgrade MM to v9 since it's a backwards compatibility issue between newer plugin versions and older MM servers.

**Comment by streamer45** [comment] 2024-03-11 15:19
Closing as duplicate of the above.

**Closed by streamer45** 2024-03-11 15:19 UTC
Labels: bug
